version: "3.9"
   
services:
  web:
    build: .
    command: bash run_server.sh
    volumes:
      - .:/code
    environment:
      - ENGINE=django.db.backends.sqlite3
    ports:
      - "8000:8000"
