# Generated by Django 3.2.7 on 2021-09-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_middleware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_module_code', models.CharField(max_length=200)),
                ('app_module_description', models.CharField(max_length=200)),
                ('app_url', models.CharField(max_length=200)),
                ('app_bigip_url', models.CharField(max_length=200)),
                ('app_port', models.CharField(max_length=200)),
                ('application_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application_patches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField()),
                ('patch_name', models.CharField(max_length=200)),
                ('patch_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_type', models.CharField(blank=True, choices=[('type1', 'Type1'), ('type2', 'Type2'), ('type3', 'Type3')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(max_length=200)),
                ('credential_secret', models.CharField(max_length=200)),
                ('credential_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Database_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=200)),
                ('cluster_ip', models.CharField(max_length=200)),
                ('database_desc', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.CharField(max_length=200)),
                ('external_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=200)),
                ('server_ip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, unique=True)),
                ('service_name_code', models.CharField(max_length=200)),
                ('external_name_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, unique=True)),
                ('elr', models.CharField(max_length=200)),
                ('deleted', models.BooleanField()),
                ('working_hours', models.CharField(max_length=200)),
                ('contacts', models.ManyToManyField(to='steplogic.Contacts')),
                ('dependent_service', models.ManyToManyField(to='steplogic.Dependent_services')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steplogic.service_name')),
            ],
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_description', models.CharField(max_length=200)),
                ('bigip_url', models.URLField(blank=True)),
                ('url', models.URLField()),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steplogic.credentials')),
                ('database_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steplogic.database_info')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200)),
                ('application_desc', models.CharField(max_length=200)),
                ('application_patches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steplogic.application_patches')),
                ('middleware_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steplogic.application_middleware')),
            ],
        ),
    ]
