# Generated by Django 3.2.7 on 2021-09-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='steplogic.env'),
            preserve_default=False,
        ),
    ]
