# Generated by Django 3.2.7 on 2021-09-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0002_sites_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='environment',
        ),
        migrations.AddField(
            model_name='env',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='steplogic.sites'),
            preserve_default=False,
        ),
    ]
