# Generated by Django 3.2.7 on 2021-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0003_auto_20210917_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='environment_type',
            field=models.CharField(choices=[('TEST', 'TEST'), ('PPT', 'PPT'), ('PROD', 'Production'), ('TRAIN', 'Training')], default='PPT', max_length=5),
            preserve_default=False,
        ),
    ]
