# Generated by Django 3.2.7 on 2021-09-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0004_env_environment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='env',
            name='database_info',
        ),
        migrations.AddField(
            model_name='credentials',
            name='environment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='steplogic.env'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database_info',
            name='environment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='steplogic.env'),
            preserve_default=False,
        ),
    ]
