# Generated by Django 3.2.7 on 2021-10-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0005_auto_20210923_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='sites',
            options={'verbose_name_plural': 'Sites'},
        ),
        migrations.AddField(
            model_name='application',
            name='environment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='steplogic.env'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servers',
            name='environment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='steplogic.env'),
            preserve_default=False,
        ),
    ]
