# Generated by Django 3.2.7 on 2021-10-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0007_auto_20211001_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application_module',
            options={'verbose_name_plural': 'Application modules'},
        ),
    ]
