# Generated by Django 3.2.7 on 2021-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0009_auto_20211005_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_module',
            name='app_bigip_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
