# Generated by Django 3.2.7 on 2021-10-12 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0010_alter_application_module_app_bigip_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='credential_secret',
            new_name='old_credential_secret',
        ),
    ]
