# Generated by Django 3.2.7 on 2021-10-12 23:14

from django.db import migrations, models
import django_cryptography.fields
from steplogic.models import Credentials

def forwards_encrypted_char(apps, schema_editor):
    # EncryptedCharModel = apps.get_model("fields", "EncryptedCharModel")

    # for row in EncryptedCharModel.objects.all():
    #     row.field = row.old_field
    #     row.save(update_fields=["field"])

    for item in Credentials.objects.all():
        item.credential_secret = item.old_credential_secret
        item.save()

def reverse_encrypted_char(apps, schema_editor):
    for item in Credentials.objects.all():
        item.old_credential_secret = item.credential_secret
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0011_rename_credential_secret_credentials_old_credential_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='credential_secret',
            field=django_cryptography.fields.encrypt(models.CharField(default="", max_length=200)),
        ),
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
