# Generated by Django 3.2.7 on 2021-10-12 23:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0013_auto_20211012_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='credential_secret',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=2000)),
        ),
    ]
