# Generated by Django 3.2.8 on 2021-10-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0017_database_info_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_system_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Operating_system_info',
            },
        ),
        migrations.AddField(
            model_name='servers',
            name='os_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steplogic.operating_system_info'),
        ),
    ]
