# Generated by Django 3.2.8 on 2021-10-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0018_auto_20211020_2240'),
    ]


    operations = [
        migrations.AlterModelOptions(
            name='operating_system_info',
            options={'verbose_name_plural': 'Operating system info'},
        ),
    ]
