# Generated by Django 3.2.8 on 2021-10-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0019_alter_operating_system_info_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_patches',
            field=models.ManyToManyField(blank=True, null=True, to='steplogic.Application_patches'),
        ),
    ]
