# Generated by Django 3.2.8 on 2021-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0020_alter_application_application_patches'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_modules',
            field=models.ManyToManyField(blank=True, null=True, to='steplogic.Application_module'),
        ),
    ]
