# Generated by Django 3.2.8 on 2021-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0021_application_application_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_module',
            name='app_port',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application_module',
            name='app_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
