# Generated by Django 3.2.8 on 2021-10-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0023_auto_20211025_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database_info',
            name='password',
        ),
        migrations.RemoveField(
            model_name='database_info',
            name='user',
        ),
        migrations.AddField(
            model_name='servers',
            name='server_role_description',
            field=models.CharField(choices=[('APPLICATION', 'Application'), ('DB', 'DB')], default='DB', max_length=11),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='database_info',
            name='environment',
        ),
        migrations.AddField(
            model_name='database_info',
            name='environment',
            field=models.ManyToManyField(to='steplogic.Env'),
        ),
    ]
