# Generated by Django 3.2.8 on 2021-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0024_auto_20211026_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='credential_type',
            field=models.CharField(choices=[('APPLICATION', 'Application'), ('DB', 'DB')], default='DB', max_length=11),
            preserve_default=False,
        ),
    ]
