# Generated by Django 3.2.8 on 2021-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steplogic', '0026_application_application_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='environment',
        ),
        migrations.AddField(
            model_name='servers',
            name='environment',
            field=models.ManyToManyField(to='steplogic.Env'),
        ),
    ]
